[package]
edition = "2021"
name = "discovery-server"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
registry = {path = "./registry"}

[build-dependencies]
cc = "1.0"
registry = {path = "./registry"}
